### PR TITLE
Promotion cache

### PR DESCRIPTION
**Pull request by johan-buret**
The ``CvPromotionInfo``  class  now stores as  properties ``isAvailableForDefensiveUnit()`` and ``isNotAvailableForDefensiveUnit()``, who are calculated only once per session.

It now uses the ``postLoadSetup()``  pattern set up by @Nightinggale  earlier today.

### CODE REVIEW

**Comment by Nightinggale** [comment]
One tiny detail. The coding standard states iTerrain is an int while eTerrain is an enum. All 3 loops loop enums while using i prefix.

Other than that it seems to be fine now. I haven't tested functionality, but I'm not spotting any flaws there by reading the code so if it passes your ingame tests, then it's likely fine.

**Comment by johan-buret** [comment]
Although complimentary reviews and tests never hurt, it passes mine on these  various cases

- Merchant ship with defense only: Caravela
- Merchant ship with attack capability : Galleon
- War ship : Brig-of-War
- Pirate Ship : Pirate Frigate.

**Comment by johan-buret** [comment]
I've corrected this code to follow the coding style  guideline.

**Comment by Nightinggale** [comment]
In CvCivilizationInfo I added postLoadSetup() right after read(). Since it's a file for all cache of the class, not just this, putting it in between code for this cache isn't the most obvious place to put it long term.

**Pull request merged**
