### PR TITLE
Issue 866 too much fur 

### PR DESCRIPTION
**Pull request by victorxup**
Proposal to solve Issue [#866] (https://github.com/We-the-People-civ4col-mod/Mod/issues/866)

Possibly need some codestyle enhacement regarding to CPP conventions

### CODE REVIEW

**Comment by devolution79** [comment]
Thank you for contributing :)

Some quick style comments: Please make the the member functions const and pass the city as a const reference rather than a pointer.
You can use YieldTypes as the iteration variable rather than an integer (look at similar loops scattered around the code). 
A single random draw would also be preferable. The performance impact is not very important for this rarely called code but the random calls do clutter the random gen. logs and may make it harder to debug OOS.
A comment / description would be helpful to to know that the function does at a glance (i.e. randomly chooses a yield weighted  proportionally by the amount of valid yields available)

**Comment by devolution79** [comment]
isYieldValidForNativeTrade : Could also deny musket and weapon stuff from being traded.

**Comment by Nightinggale** [comment]
First of all the fix is most welcome. It almost feels somewhat ungrateful to point out so many imperfections when it's overall of good quality. However at the same time we do value code quality and consistency to avoid current and future bugs.

> You can use YieldTypes as the iteration variable rather than an integer (look at similar loops scattered around the code).

I added the ability to iterate enums and we are slowly converting all int iterations to enum iterations. The line should look like:

```cpp
for (YieldTypes eYield = FIRST_YIELD; eYield < NUM_YIELD_TYPES; ++eYield)
```

This will remove the need to typecast, which in turn makes debugging nicer and reduces the risk of messing up enum types (bugs).

> A single random draw would also be preferable. The performance impact is not very important for this rarely called code but the random calls do clutter the random gen. logs and may make it harder to debug OOS.

The random call is in the initializer, hence only called once. Other than that I agree. It should be set outside the loop and the resulting value should be const as it's not the iterator. It would make more sense to iterate over a YieldTypes as that makes the code reveal the intention better.

isYieldValidForNativeTrade should check for >= FIRST_YIELD before calling canProduceYield. This way output will be defined for all input and as such reusing the function later and calling it with NO_YIELD will not cause a bug.

We use the coding style where { has a dedicated line. (ok this one could be nitpicking)

EDIT: NUM_CARGO_YIELD_TYPES exist and could be better suited than NUM_YIELD_TYPES. This will exclude looping yields such as bells or hammers, which can't be transported, hence can't be traded.

**Comment by victorxup** [comment]
> isYieldValidForNativeTrade : Could also deny musket and weapon stuff from being traded.

This behaviour was already implemented via getNativeSellPrice() > 0 check, so no need to implement anything new about it.
There's a bunch of goods that natives never gonna sell

**Comment by victorxup** [comment]
Made some changes
Please take a look

**Comment by Nightinggale** [comment]
Now it looks fine. Thanks for your contribution. Feel free to drop by in our discord.

**Pull request merged**
