### PR TITLE
Makefile will also copy changed files from folder Assets in dev directory to folder Assets in YOURMOD (including files in subfolders).

### PR DESCRIPTION
**Pull request by ShadesOT**

### CODE REVIEW

**Comment by ShadesOT** [comment]
> Do you have a realistic use case where YOURMOD is different from the default ..?

Yes. I got my dev mod entirely separated from the civ4col mod folder. As for the reason ... I think I originally wanted to have an untouched latest version of RAR in the MODS folder and a copy eg RARdev for development. But with that changed name I could not easily load savegames from the mod named RAR. ... so I started to copy the changes, which totally contradicted my original intentions. :-D .... (And history and legacy already made their dents again).
So it is realistic, but it is not a usecase. ;-) Thinking about it, makes me want to clean up the situation on my local drive.

Anyways, what is the YOURMOD variable there for then? Let's make this work and then forget about it

**Comment by Nightinggale** [comment]
YOURMOD is a relic of Makefile 1.0 from 2010. It's still in Makefile 2.5 and that makefile aims to be as generic as possible (matches all mods). However we now use a modified version of 2.5 and no longer has to care about generic compatibility. This means we could clean up the makefile.

However I'm not really feeling for touching it. Microsoft's nmake isn't a good makefile tool. If time is to be spend on anything other than quick fixes, rewriting the makefile to use GNU make would be a whole lot better. I have a perl script, which solves #58, but adding it would require everybody to install [Strawberry perl](http://strawberryperl.com/). This however has the bonus that it comes bundled with a bunch of tools normally found in linux, including GNU make.

**Comment by ShadesOT** [comment]
Ok, but is it ok to make these changes?
Btw, which dll is used by the exe, the one in Assets or those in "x plot city radius"?

**Comment by Nightinggale** [comment]
I haven't tested it, but if you have and it works for you, then I don't see why not. If you can benefit from the change, then feel free to make the change.

The exe will always read from the same location as in vanilla and vanilla has the DLL in assets.

**Comment by ShadesOT** [comment]
merge done localy and pushed. commit dc8654ad878590a3a0ba0b3134134dd302e49554 .

**Pull request closed without merging**
