### PR TITLE
Added inline functions in CvArea.h #106

### PR DESCRIPTION
**Pull request by Swati-007**

### CODE REVIEW

**Comment by Swati-007** [comment]
I'm new to open-source. I've made a new commit with the update. Is it the right way to go about it?

**Comment by ShadesOT** [comment]
Yes it is. It just appeared that you forgot one function. So I requested that you change the code, before this pull request can be approved.

Thank you for participating btw. :-)

Some requests:
- Compile the project after you made changes to see if the compiler throws an error
- Playtest the changes if possible  (using wordlbuilder and cheatengine if necessary)
- If you make small amendments to your last commit use `git commit --amend`
( https://www.atlassian.com/git/tutorials/rewriting-history )
- If you make several commits until you are satisfied with the implementation/changes (commiting often while working on something is a good thing), use a squash commit/rebase to merge commits which belong together. The rule is to merge commits, which by themselves would leave the code broken. On top of that commits which consider the same issue can be merged.

That way quality can be assured and the commit history on the main branches can be kept clean and slim.

**Comment by Swati-007** [comment]
Thank you very much. I'll keep these in mind.  :-)

**Comment by ShadesOT** [comment]
can you try to merge the two commits together? and then pull request again?

**Comment by ShadesOT** [comment]
use
`git rebase -i HEAD~2`

**Comment by Swati-007** [comment]
I used the above command. It went somewhere awry along the way. But I guess I've done it correctly. Can you please check now. Thank you.

**Comment by ShadesOT** [comment]
Nice. The commit history looks good now. Thank you.

**Comment by ShadesOT** [comment]
Can you change the pull request so that you are requesting to pull into branch develope-2_7_1? Because this is where all the changes for the next version go. I am not sure if you can change this pull request or if you need to make a new pull request though. Thanks

**Comment by ShadesOT** [comment]
Ah and another thing, ... can you please reference the issue that made you do the changes? ... was it #106?

**Comment by Swati-007** [comment]
Yes, it's # 106. I'll do that. Also, I checked, I'd have to create a new PR.

**Comment by Swati-007** [comment]
Oh no, I don't have to create a new PR. I'll read more thoroughly now.

**Comment by Swati-007** [comment]
I didn't really contribute much , but you've been very patient and helpful . Thank you. :-)

**Comment by ShadesOT** [comment]
You are welcome.
May I ask if you are interested in this mod and cv4col, or did you pass by because of the tag "Good first issue"?

**Comment by Nightinggale** [comment]
`
I didn't really contribute much
`
Actually your contribution is valued more than you give it credit for. It's a task we want to be done and it helps the compiler to optimize better, meaning the end result is less waiting time for the AI. Nothing major from a single file, but one step at a time and it all counts. It may not be the task, which demands the most programming skills, but it's still a task, which should be done in order to end up with the best possible code.

**Comment by ShadesOT** [comment]
A last request: As we would like to test the changes before we merge them into the main branches, can you please change your pull request to branch "swati_007_#106"?

**Comment by Nightinggale** [comment]
No need to do make more pull requests. I figured out how to test pull requests locally without any more changes from the request creator.

The diff looks fine and I merged it :+1:

**Pull request merged**
