### PR TITLE
add -3 yield of cochineal to all terrains except shrublands

### PR DESCRIPTION
**Pull request by jo-oe**

### CODE REVIEW

**Comment by raystuttgart** [comment]
Sorry but this is a bad fix.
I have to refuse it.
I already commited the correct fix.

**Comment by jo-oe** [comment]
But is there a reason this is inconsistent with the other yields? I just tried to playtest my fix and it appears to work ...

**Comment by raystuttgart** [comment]
No, the "-" setting for the Terrains should only be used for "Hill Yields" like e.g. Grapes or Red Pepper.
It is not supposed to be used for all Yields generally.

**Comment by raystuttgart** [comment]
Please try my fix.

**Pull request closed without merging**
