### PR TITLE
Hungarian translation

### PR DESCRIPTION
**Pull request by ElCid0204**

### CODE REVIEW

**Comment by ElCid0204** [comment]
Hungarian translation

**Comment by raystuttgart** [comment]
@ElCid0204 
We do not merge on Master, just on "develop".

If you were working on Master you were working on an outdated version ...
Normally everybody should always work on the current development version - not release versions.

Not sure what to do with this now honestly ...

Maybe @Nightinggale has an idea what to do without causing overhead.
Merging on develop would most likely delete all the text improvements of the last weeks.

**Comment by ElCid0204** [comment]
Don't worry!😀
This has happened due to my lack of knowledge of github.
Just go ahead and loose any improvement you have achieved during the last
coiple of weeks. I'll follow the team and update my part.
I've translated  the released version to test it. There are always html tag
errors and problematic charactets.
Thanks and bye


raystuttgart ***@***.***> ezt írta (időpont: 2023. ápr. 27.,
Csü 7:23):

**Comment by raystuttgart** [comment]
Ok, I saw that you had just changed one single file. :)
So if you send me that file over at CivFanatics, I can merge manually into develop.

**Comment by ElCid0204** [comment]
Actually Ive changed 4, but cannot put the in 1 request😀
I'll send over all of them over Civfanatics and it will be uo to you how to
merge them.
Now I'm focusing on older filea, such as original col files, and old TAC
files. I suppose those are not changing so fast.



raystuttgart ***@***.***> ezt írta (időpont: 2023. ápr. 28.,
Pén 11:26):

**Comment by raystuttgart** [comment]
@ElCid0204 
Sorry, but if it is more than the 1 file I saw above then I will **not** merge.
Please then switch to working based on "develop" properly.
Everything else is wasting effort and generating overhead.

**Comment by ElCid0204** [comment]
Ok. I will make a try. I just dont know how to test it.

raystuttgart ***@***.***> ezt írta (időpont: 2023. ápr. 28.,
Pén 14:39):

**Comment by raystuttgart** [comment]
Please join discord and contact @Nightinggale.

He can give you access to the **channel for translations**, where things like this are organized and discussed.
If you really want to support the mod, you need to be **in touch with the team** and discuss what you do.

Here is the link to discord:
https://discord.gg/UWSw2x5wqh

**Comment by Nightinggale** [comment]
cf60b7a20b38f4bf222c4f7ee210914ba4abd269
I manually merged the change into develop. Git refused to do it automatically because there is an issue with line endings (no idea why or who/what is to blame) so I had to go through the diff and revert any change to any non-Hungarian lines.

Still I would highly recommend all translators be be in #translations in discord. It helps coordinate issues like multiple people working on the same file at the same time.

Also while I didn't fix it here, Ideally place Hungarian before Russian.
```cpp
	case 0: return "English";
	case 1: return "French";
	case 2: return "German";
	case 3: return "Italian";
	case 4: return "Spanish";
	case 5: return "Finnish";
	case 6: return "Hungarian";
	case 7: return "Polish";
	case 8: return "Russian";
```

That's the order of languages in the code. It would make sense to use the same order in xml, through technically any order should work.

**Pull request closed without merging**
