### PR TITLE
new logic for removing players from the game

### PR DESCRIPTION
**Pull request by jo-oe**

### CODE REVIEW

**Comment by raystuttgart** [comment]
@jo-oe Careful with this !
This is dangerous !!!!!

--------------

You removed this:
if(getParent() != NO_PLAYER)

And set this:
if (!isNative() && !isEurope())

----------------

You seem to forget Wild Animals and Church.
(Also potentially Pirates in the future or e.g. Neutral Traders.)

Please put back the Parent check.

**Comment by raystuttgart** [comment]
**Another comment:**

Where did this check go ?
GC.getDefineINT("KI_RESPAWN_OFF") == 1

We should still allow the player to set endless respawning.

**Comment by raystuttgart** [comment]
**Edit:**
I first thought the respawn Option in XML was gone.
But I found it again in the code. Everything ok.

**Comment by jo-oe** [comment]
> You removed this: if(getParent() != NO_PLAYER)
> 
> And set this: if (!isNative() && !isEurope())

I was just checking my changes: Actually the line you mentioned - including the following block - was there before, line 8577, I just added a comment to it because I did not know what this part (including getMaxCityElimination()) was about:
`		if (!bKill)`
`		{`
`			if (!isNative() && !isEurope())`
`			{`
`				if (GC.getGameINLINE().getMaxCityElimination() > 0)`
`				{`
`					if (getCitiesLost() >= GC.getGameINLINE().getMaxCityElimination())`
`					{`
`						bKill = true;`
`					}`
`				}`
`			}`
`		}`

I did not want to change any conditions for this case because I did not know why it is there at all ...

**Comment by raystuttgart** [comment]
Ok, I will merge it then. 👍

**Pull request merged**
